export const OBTENER_CITAS = "OBTENER_CITAS";
export const OBTENER_CITAS_EXITO = "OBTENER_CITAS_EXITO";
export const OBTENER_CITAS_ERROR = "OBTENER_CITAS_ERROR";

export const NUEVA_CITA = "NUEVA_CITA";
export const NUEVA_CITA_EXITO = "NUEVA_CITA_EXITO";
export const NUEVA_CITA_ERROR = "NUEVA_CITA_ERROR";
